### PR TITLE
fix(_comp_command_offset): fix offset mismatching for words vs COMP_WORDS (use words)

### LINKED ISSUE #722: Completing sudo after --user= doesn't suggest commands
## Describe the bug

When trying to complete `sudo --user=foobar <HIT TAB HERE>`, it suggests the files in the current directory instead of commands

## To reproduce

1. Type `sudo --user=<A USER ON YOUR SYSTEM>`
2. Try to complete
3. See problem

## Expected behavior

Trying to complete `sudo --user=foo` should suggest command names, not files in the current directory

## Versions (please complete the following information)

- [ ] Operating system name/distribution and version: Fedora 35 Silverblue
- [ ] bash version, `echo "$BASH_VERSION"`: 5.1.8(1)-release
- [ ] bash-completion version, `(IFS=.; echo "${BASH_COMPLETION_VERSINFO[*]}")`: 2.11

## Additional context

I discovered this when trying to [write a completion](https://gitlab.com/carbonOS/build-meta/-/blob/a0ff8032a40baeded34c73da0a87dde3c31f03db/files/polkit/pkexec.completion) for `pkexec`. There's another bug in sudo's completion that mishandles `sudo --user foobar`, so this context doesn't apply to sudo. My completion doesn't have this bug, so I can get this additional behavior: `pkexec --user=foobar <TAB>` completes the directory, but `pkexec --user foobar <TAB>` completes commands. I can confirm that, at least with my completion, `_command_offset` is being executed. So I suspect soething in _command_offset can't deal with `--arg=data` arguments?

## Debug trace

[bash-completion.log](https://github.com/scop/bash-completion/files/8387366/bash-completion.log)

### PR DESCRIPTION
**Pull request by akinomyoga**
Fixes #722.

This fixes it the other way around as #802. Now `_comp_command_offset` receives the index in `words` instead of that in `COMP_WORDS`.

### CODE REVIEW

**Comment by akinomyoga** [comment]
I have rebased it on top of the latest master and added adjustments to the existing interfaces in commit 25d5f8ff.

File: completions/sudo [hunk 1]
```diff
@@ -23,7 +23,7 @@ _sudo()
                 break
             fi
             # shellcheck disable=SC2254
-            [[ ${words[i]} == -@(user|other-user|group|close-from|prompt|${noargopts}[uUgCp]) ]] &&
+            [[ ${words[i]} == @(--@(user|other-user|group|close-from|prompt)|-${noargopts}[uUgCp]) ]] &&
```
Comment (scop) [inline completions/sudo:26]: Cherry picked to master as 1cf6fa6aadcd6162cdbe78e9462f611bfcd0fdb0.

File: bash_completion [hunk 2]
```diff
@@ -2208,6 +2208,18 @@ _comp_command_offset()
...
     # actual command completion
 
+    # convert the new first-word position $1 to the index in COMP_WORDS.
+    if [[ -v cword && -v words ]]; then
+        local reassembled_offset=$1 i=0 j
+        for ((j = 0; j < reassembled_offset; j++)); do
+            local word=${words[j]}
+            while [[ $word && i -lt ${#COMP_WORDS[@]} ]]; do
+                word=${word#*"${COMP_WORDS[i++]}"}
+            done
```
Comment (scop) [inline bash_completion:2218]: I'm sorry and afraid that I'm having a bit of a problem understanding the intent and workings here. So we remove things found in `COMP_WORDS` from each `word` until the `word` becomes empty or we run out of `COMP_WORDS`. But as we treat the thing to be removed as a `word` prefix, wouldn't we run into problems / false positives with let's say the sequence `sudo su do`?

Could we add some unit tests for this, to illustrate how the changed code works?

**Review by scop — CHANGES_REQUESTED** [review]

File: completions/find [hunk 3]
```diff
@@ -8,9 +8,8 @@ _comp_cmd_find()
     _comp_initialize -- "$@" || return
 
     local i
-    for i in ${!words[*]}; do
+    for ((i = 1; i < cword; i++)); do
         if [[ ${words[i]} == -@(exec|ok)?(dir) ]]; then
-            ((cword > i)) || break
```
[the remark this answers is not in the document]
Comment (akinomyoga) [reply completions/find:13]: In the codebase, most of the similar loops are in the form `for ((i = 1; i < cword; i++))`:

<details><summary><code>git grep -nE 'for \(\(.*cword'</code></summary>

```bash
$ git grep -nE 'for \(\(.*cword'
./bash_completion:558:        for ((i = 0; i <= cword; ++i)); do
./bash_completion:1774:    for ((i = 1; i < cword; i++)); do
./bash_completion.d/000_bash_completion_compat.bash:124:        for ((i = 0; i <= cword; ++i)); do
./completions/_adb:29:    for ((i = 1; i < cword; i++)); do
./completions/_ionice:12:    for ((i = 1; i <= cword; i++)); do
./completions/_udevadm:12:    for ((i = 1; i < cword; i++)); do
./completions/ant:73:        for ((i = 1; i < cword; i++)); do
./completions/arch:28:            for ((i = 1; i < cword; i++)); do
./completions/carton:22:    for ((i = 1; i < cword; i++)); do
./completions/cfrun:9:    for ((i = 1; i < cword; i++)); do
./completions/cfrun:28:                for ((i = 1; i < cword; i++)); do
./completions/chronyc:38:    for ((i = 1; i < cword; i++)); do
./completions/dict:18:    for ((i = 1; i < cword; i++)); do
./completions/dmypy:19:    for ((i = 1; i < cword; i++)); do
./completions/export:9:    for ((i = 1; i < cword; i++)); do
./completions/gdb:9:    for ((i = 1; i < cword; i++)); do
./completions/getent:10:    for ((i = 1; i < cword; i++)); do
./completions/htpasswd:9:    for ((i = 1; i <= cword; i++)); do
./completions/ip:47:    for ((subcword = 1; subcword < ${#words[@]} - 1; subcword++)); do
./completions/java:18:    for ((i = 1; i < cword; i++)); do
./completions/java:40:    for ((i = 1; i < cword; i++)); do
./completions/java:139:    for ((i = 1; i < cword; i++)); do
./completions/koji:41:    for ((commandix = 1; commandix < cword; commandix++)); do
./completions/koji:121:        for ((i = commandix + 1; i < cword; i++)); do
./completions/koji:224:                        for ((i = commandix + 1; i < cword; i++)); do
./completions/ktutil:57:    for ((i = 1; i < cword; i++)); do
./completions/lvm:59:    for ((i = offset; i < cword; i++)); do
./completions/mdadm:8:    for ((i = 1; i < cword; i++)); do
./completions/mdadm:38:    for ((i = 1; i < cword; i++)); do
./completions/modprobe:46:    for ((i = 1; i < cword; i++)); do
./completions/openssl:8:    for ((i = 2; i < cword; i++)); do
./completions/quota:8:    for ((i = 1; i < cword; i++)); do
./completions/rsync:77:            for ((i = 1; i < cword; i++)); do
./completions/screen:67:        for ((i = 1; i <= cword; i++)); do
./completions/strace:10:    for ((i = 1; i <= cword; i++)); do
./completions/sudo:13:        for ((i = 1; i <= cword; i++)); do
./completions/svcadm:108:    for ((i = 1; i < cword; i++)); do
./completions/tipc:27:    for ((i = 0; i < cword; i++)); do
./completions/tipc:124:                    for ((i = 0; i < cword; i++)); do
./completions/update-alternatives:10:    for ((i = 1; i < cword; i++)); do
./completions/update-alternatives:37:    for ((i = 1; i < cword; i++)); do
./completions/watch:13:    for ((i = 1; i <= cword; i++)); do
./completions/wvdial:28:            for ((i = 1; i < cword; i++)); do
./completions/xrandr:50:    for ((i = cword - 1; i > 0; i--)); do
```
</details>

On the other hand, there are a few cases of `for i in ${!words[*]}`
```bash
$ git grep -nE 'for .* in .*!words\['
completions/crontab:20:    for i in "${!words[@]}"; do
completions/find:11:    for i in ${!words[*]}; do
completions/lilo:27:            for i in "${!words[@]}"; do
completions/secret-tool:12:    for i in ${!words[*]}; do
```
In `crontab`, `lilo`, `secret-tool`, all the words `"${words[@]}"` are processed. Only in the `find` case, we loop over the `words[i]` where `i < cword` using the form `for i in ${!words[*]}`, so I think it is better to make `find` consistent with other cases for looping over `i < cword`.

Anyway, I don't like the current strange way of the loop conditioning for `i < cword`. Even if we keep the style `for i in ${!words[*]}`, it should be refactored as

```diff
diff --git a/completions/find b/completions/find
index 646eefb1..dd3c78c2 100644
--- a/completions/find
+++ b/completions/find
@@ -8,9 +8,9 @@ _comp_cmd_find()
     _comp_initialize -- "$@" || return

     local i
-    for i in ${!words[*]}; do
+    for i in "${!words[@]}"; do
+        ((i < cword)) || break
         if [[ ${words[i]} == -@(exec|ok)?(dir) ]]; then
-            ((cword > i)) || break
             _comp_command_offset $((i + 1))
             return
         fi
```

> in the sense that it works even if we `unset` something from the array.

I searched for `unset .*words[` in the codebase, and the only case that unsets `words` elements is [`completions/qdbus`:8](https://github.com/scop/bash-completion/blob/master/completions/qdbus#L8) where the last element is removed.

File: completions/sudo (hunk 1 above)
Comment (akinomyoga) [reply completions/sudo:26]: Thanks

File: bash_completion (hunk 2 above)
Comment (akinomyoga) [reply bash_completion:2218]: > the intent and workings here.

We here convert the index in `words` to the index in `COMP_WORDS`. The array `words` is constructed by the function `_comp__reassemble_words` (originally `__reassemble_comp_words_by_ref`). [The function `_comp__reassemble_words` combines multiple `COMP_WORDS[*]` into an element of `words`](https://github.com/scop/bash-completion/blob/e9bf32c3ade5e4f72321638eb3928d66bc0ec1bd/bash_completion#L526), so we need to decomposes `words[j]` by referencing the original `COMP_WORDS[i]`. For the approach `${word#*"${COMOP_WORDS[i++]}"}`, I borrowed [the existing strategy for `line` used in `__comp__reassemble_words`](https://github.com/scop/bash-completion/blob/e9bf32c3ade5e4f72321638eb3928d66bc0ec1bd/bash_completion#L528).

> But as we treat the thing to be removed as a `word` prefix, wouldn't we run into problems / false positives with let's say the sequence `sudo su do`?

The assumption is that `words` are constructed from `COMP_WORDS` using `_comp__reassemble_words`, so that we always have a corresponding substring in `words[j]` for any `COMP_WORDS[i]`. In this case, even with `sudo su do`, the correspondence between `words` and `COMP_WORDS` are kept so unrelated words will not be mixed.

I'll later add tests.

File: completions/find (hunk 3 above)
[the remark this answers is not in the document]
Comment (scop) [reply completions/find:13]: One difference is whether we want to start looping from index 1, usually to skip the command name. If that's important in some way, then the `${!foo[*]}` check should be accompanied by another test.

Even if we don't currently unset `words` entries, I think doing so could be fine in principle.

Anyway, your suggested refactoring in the comment above seems fine to me, but I'm fine with the change here like it is now, too, leaving up to you to make the call which one to go with.

[the remark this answers is not in the document]
Comment (akinomyoga) [reply completions/find:13]: > One difference is whether we want to start looping from index 1, usually to skip the command name.

`find` seems to have been also checking the first word using the `${!words[*]}` approach, but I don't think we need to check the first word (the command name) for the option `-@(exec|ok)?(dir)`,

> Even if we don't currently unset `words` entries, I think doing so could be fine in principle.

In that case, I guess we want to address existing `for ((i = 1; i < cword; i++)); do` at once. Also, we need to decide other occurrences of `words[...]`.

<details><summary><code>git grep -n 'words\[[^*@i]'</code></summary>

```bash
./completions/7z:14:    [[ ${words[1]} == @(a|d|rn|u) ]] && mode=w || mode=r
./completions/7z:115:        if [[ ${words[1]} == d ]]; then
./completions/7z:117:            COMPREPLY=($(compgen -W "$(printf '%s\n' "$("$1" l "${words[2]}" \
./completions/_mock:17:            cfgdir="${words[count + 1]}"
./completions/_modules:75:        case ${words[1]} in
./completions/_nmcli:85:        local object=${words[1]}
./completions/_nmcli:86:        local command=${words[2]}
./completions/_nmcli:161:                        local subcommand=${words[3]}
./completions/_renice:15:        curopt=${words[cword - i]}
./completions/_svn:47:        local command=${words[1]}
./completions/_svnadmin:33:        local command=${words[1]}
./completions/_svnlook:22:        local command=${words[1]}
./completions/_xm:41:        command=${words[1]}
./completions/brctl:8:    local command=${words[1]}
./completions/cpio:38:        case ${words[1]} in
./completions/cvs:63:        if [[ ${words[count]} == "${cvsroot-}" && ${mode-} == cvsroot ]]; then
./completions/cvs:75:                    cvsroot=${words[count + 1]}
./completions/dict:22:                host=${words[++i]}
./completions/dict:26:                port=${words[++i]}
./completions/dict:30:                db=${words[++i]}
./completions/dpkg:48:            prev=${words[--i - 1]}
./completions/function:11:        local funcdef=$(type -- "${words[1]}" 2>/dev/null | command sed -e 1,2d)
./completions/gm:17:    elif [[ $cword -eq 2 && ${words[1]} == time ]]; then
./completions/gm:22:    local gmcmd=${words[1]}
./completions/gm:23:    [[ $gmcmd == time ]] && gmcmd=${words[2]}
./completions/gnokii:156:    if [[ $((cword - 2)) -ge 1 && ${words[cword - 2]} =~ --* ]]; then
./completions/gnokii:157:        pprev=${words[cword - 2]}
./completions/gnokii:185:    if [[ $((cword - 3)) -ge 1 && ${words[cword - 3]} =~ --* ]]; then
./completions/gnokii:186:        tprev=${words[cword - 3]}
./completions/gnokii:197:                [[ ${words[cword - 1]} == end ]] &&
./completions/gnokii:209:    if [[ $((cword - 4)) -ge 1 && ${words[cword - 4]} =~ --* ]]; then
./completions/gnokii:210:        fprev=${words[cword - 4]}
./completions/htpasswd:31:            '$(cut -d: -f1 "${words[o]}" 2>/dev/null)' -- "$cur"))
./completions/insmod:13:            -p "${words[1]}" 2>/dev/null | cut -d: -f1)" -- "$cur"))
./completions/ip:48:        [[ ${words[subcword]} == -b?(atch) ]] && return
./completions/ip:49:        [[ -v cmd ]] && subcmd=${words[subcword]} && break
./completions/ip:50:        [[ ${words[subcword]} != -* &&
./completions/ip:51:            ${words[subcword - 1]} != -@(f?(amily)|rc?(vbuf)) ]] &&
./completions/ip:52:            cmd=${words[subcword]}
./completions/ipcalc:17:        [[ ${words[cword - i]} == -@(-split|s) ]] && return
./completions/ipsec:29:    case ${words[1]} in
./completions/ipsec:68:    case ${words[1]} in
./completions/iscsiadm:35:        case ${words[2]} in
./completions/iwconfig:18:                    "$(iwlist "${words[1]}" scan |
./completions/iwconfig:28:            COMPREPLY=($(compgen -W "$(iwlist "${words[1]}" channel |
./completions/iwconfig:34:            COMPREPLY=($(compgen -W "$(iwlist "${words[1]}" channel |
./completions/iwconfig:42:                    "$(iwlist "${words[1]}" scan |
./completions/iwconfig:50:                "$(iwlist "${words[1]}" rate |
./completions/jar:13:    case ${words[1]} in
./completions/java:273:    if [[ $cword -gt 2 && ${words[cword - 2]} == -linkoffline ]]; then
./completions/jq:29:        case ${words[cword - 2]} in
./completions/koji:42:        if [[ ${words[commandix]} != -* ]]; then
./completions/koji:43:            command=${words[commandix]}
./completions/lvm:55:    if [[ ${words[0]} == lvm ]]; then
./completions/lvm:58:    local i prev=${words[offset - 1]}
./completions/lvm:894:        case "${words[1]}" in
./completions/lvm:900:                "_${words[1]}"
./completions/mcrypt:49:    elif [[ ${words[0]} == mdecrypt ]]; then
./completions/mdadm:113:            case ${words[cword - 1]} in
./completions/mplayer:16:    local cmd=${words[0]} i j k=0
./completions/mutt:94:    local cur=$1 muttrc muttcmd=${words[0]}
./completions/mutt:113:    local cur=$1 querycmd muttcmd=${words[0]}
./completions/mutt:132:    local cur=$1 folder muttrc spoolfile muttcmd=${words[0]}
./completions/mypy:8:    [[ $cword -gt 2 && ${words[cword - 2]} == --shadow-file ]] &&
./completions/openssl:61:        command=${words[1]}
./completions/p4:35:                case ${words[cword - 2]} in
./completions/puppet:76:    case ${words[0]} in
./completions/puppet:105:            case ${words[1]} in
./completions/puppet:108:                    subcommand=${words[1]}
./completions/python:65:            [[ $cword -lt 2 || ${words[cword - 2]} != -[QWX] ]] && _filedir
./completions/qdbus:8:    [[ $cur ]] && unset -v "words[$((${#words[@]} - 1))]"
./completions/rpm:130:    case ${words[1]} in
./completions/screen:42:        case ${words[1]} in
./completions/screen:58:            case ${words[cword - 2]} in
./completions/sqlite3:26:    [[ $cword -gt 2 && ${words[cword - 2]} == -@(lookaside|pagecache|scratch) ]] &&
./completions/ssh:578:                COMPREPLY=($(compgen -W '$(_parse_usage "${words[0]}")' \
./completions/svk:35:        command=${words[1]}
./completions/tar:177:    first_word=${words[1]}
./completions/tar:463:            case ${words[1]} in
./completions/tipc:103:    case "${words[optind]}" in
./completions/tipc:114:            case "${words[optind]}" in
./completions/tipc:195:            case "${words[optind]}" in
./completions/tipc:222:                    case "${words[optind]}" in
./completions/tipc:238:            case "${words[optind]}" in
./completions/tipc:274:            case "${words[optind]}" in
./completions/xdg-mime:44:    case ${words[1]} in
./completions/xdg-mime:51:            case ${words[2]} in
./completions/xrandr:125:        case "${words[cword - 2]}" in
./completions/xrandr:135:                local modes=$(_comp_cmd_xrandr_modes "$1" "${words[cword - 1]}")
./completions/xrandr:162:        case "${words[cword - 3]}" in
./completions/ypmatch:14:        map=${words[2]}
```
</details>

These can be addressed in another PR if needed. For the time being, either works for me.

File: bash_completion (hunk 2 above)
Comment (scop) [reply bash_completion:2218]: I can't shake the feeling that for some input we'd lose track of things here, because we're just repeatedly removing a prefix from the  `words` entry apparently without knowledge whether it ended up there due to the earlier reassembly, or if it was there already. Somehow this is quite confusing to me, but then again so is the `_comp__reassemble_words` implementation despite the commentary in it.

I guess seeing some tests will help. Extracting the "reverse word index reassembly" block that was added here to a separate function could be good for testability.

File: completions/find (hunk 3 above)
[the remark this answers is not in the document]
Comment (scop) [reply completions/find:13]: Let's leave this one as is for the time being. Choosing between the two is not urgent, we can revisit it sometime after the next release if we like.

File: bash_completion (hunk 2 above)
Comment (akinomyoga) [reply bash_completion]: I separated a function `_comp__find_original_word`. The name of the function can be adjusted.

I also added two tests, but I'm not sure what the concern is, so they might not cover the situation that you concern about.

File: bash_completion [hunk 4]
```diff
@@ -2341,6 +2369,12 @@ _comp_command_offset()
 #
 _comp_command()
 {
+    # We locally make the shell variable "words" in the unset state to tell
+    # "_comp_command_offset" that the index is intended to be that in
+    # "COMP_WORDS" instead of "words".
```
Comment (scop) [inline bash_completion:2374]:
```suggestion
    # We unset the shell variable `words` locally to tell
    # `_comp_command_offset` that the index is intended to be that in
    # `COMP_WORDS` instead of `words`.
```

File: bash_completion.d/000_bash_completion_compat.bash [hunk 5]
```diff
@@ -235,4 +235,18 @@ _init_completion()
 # shellcheck disable=SC2154  # defined in the main "bash_completion"
 _backup_glob=$_comp_backup_glob
 
+# @deprecated Use "_comp_command_offset" instead.  It should be noted that the
+# new interface "_comp_command_offset" is changed to receive an index in
+# "words" instead of that in "COMP_WORDS" as "_command_offset" did.
```
Comment (scop) [inline bash_completion.d/000_bash_completion_compat.bash:240]:
```suggestion
# @deprecated Use `_comp_command_offset` instead.  Note that the
# new interface `_comp_command_offset` is changed to receive an index in
# `words` instead of that in `COMP_WORDS` as `_command_offset` did.
```

File: bash_completion.d/000_bash_completion_compat.bash [hunk 6]
```diff
@@ -235,4 +235,18 @@ _init_completion()
...
+_command_offset()
+{
+    # This compatibility function assumes the first argument to be the index in
+    # "COMP_WORDS" instead of that in "words".  To tell it to the new interface
+    # "_comp_command_offset", we locally make the variable "words" in the unset
+    # state.
```
Comment (scop) [inline bash_completion.d/000_bash_completion_compat.bash:246]:
```suggestion
    # We unset the shell variable `words` locally to tell
    # `_comp_command_offset` that the index is intended to be that in
    # `COMP_WORDS` instead of `words`.
```

**Review by scop — APPROVED** [review]
Thanks! Seeing the examples in the tests makes it clearer to me to understand what's going on.

Added some comment suggestions, pre-approved + feel free to merge when the conflicts are resolved.

**Comment by akinomyoga** [comment]
- Line folding at column 79 ([750a244a..bfc752b5](https://github.com/scop/bash-completion/compare/750a244af4cccff9d106ebfa395b29b12b7647a0..bfc752b55294816f20a5b541b1dfcfd338360410))

**Comment by akinomyoga** [comment]
Thanks.
